apiVersion: v1
kind: Service
metadata:
  name: {{ include "python-deployment.fullname" . }}-python-flask-service
  labels:
    app: python-flask
  {{- include "python-deployment.labels" . | nindent 4 }}
spec:
  type: {{ .Values.pythonFlaskService.type }}
  selector:
    app: python-flask
  {{- include "python-deployment.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.pythonFlaskService.ports | toYaml | nindent 2 -}}