stages:

 - build-push
 - deploy

image: docker:19.03.12
variables:
 DOCKER_HOST: tcp://docker:2375/
 DOCKER_TLS_CERTDIR: ""
 REGISTRY_HOSTNAME: gcr.io/arctiq-mission-masrur
 DOCKER_IMAGE_NAME: ${CI_PROJECT_NAME}
services:
 - docker:19.03.12-dind

build-push:
 stage: build-push
 before_script:
   - docker info
   - echo "$SERVICE_ACCOUNT_KEY" > key.json
   - docker login -u _json_key --password-stdin https://gcr.io < key.json
 script:
   - docker build --tag $REGISTRY_HOSTNAME/$DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA .
   - docker push $REGISTRY_HOSTNAME/$DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA

deploy:
 stage: deploy
 image: google/cloud-sdk
 script:
# Authenticate with GKE
   - echo "$SERVICE_ACCOUNT_KEY" > key.json
   - gcloud auth activate-service-account --key-file=key.json
   - gcloud config set project arctiq-mission-masrur
   - gcloud config set container/cluster primary
   - gcloud config set compute/zone asia-south1-c
   - gcloud container clusters get-credentials primary --zone asia-south1-c --project arctiq-mission-masrur
   - sed -i "s/<VERSION>/${CI_COMMIT_SHORT_SHA}/g" deployment.yaml
   - kubectl apply -f deployment.yaml