apiVersion: v1
kind: Namespace
metadata:
  name: <ENVIRONMENT>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: <ENVIRONMENT>-cicd
  namespace: <ENVIRONMENT>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-flask
  template:
    metadata:
      labels:
        app: python-flask
    spec:
      containers:
      - name: python-flask-app
        image: gcr.io/arctiq-mission-masrur/arctiq_mission/arctiq-image:<VERSION>
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: python-flask-service
  namespace: <ENVIRONMENT>
  labels:
    app: python-flask
spec:
  type: LoadBalancer
  selector:
    app: python-flask
  ports:
  - port: 80
    targetPort: 8080
