apiVersion: apps/v1
kind: Deployment
metadata:
  name: arctiq-mission-cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python-flask
        image: gcr.io/arctiq-mission-masrur/arctiq_mission/mdmasrur3426/arctiq-image:<VERSION>
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: python-service
spec:
  type: LoadBalancer
  selector:
    app: python
  ports:
  - port: 80
    targetPort: 8080