apiVersion: v1
kind: Namespace
metadata:
  name: arctiq-mission
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arctiq-mission-cicd
  namespace: arctiq-mission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-flask
  template:
    metadata:
      labels:
        app: python-flask
    spec:
      containers:
      - name: python-flask-app
        image: gcr.io/arctiq-mission-masrur/arctiq_mission/mdmasrur3426/arctiq-image:<VERSION>
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
        readinessProbe:
           httpGet:
             path: /
             port: 8080
           initialDelaySeconds: 5
           timeoutSeconds: 5
           periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: python-flask-service
  namespace: arctiq-mission
  labels:
    app: python-flask
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: python-flask