apiVersion: v1
kind: Namespace
metadata:
  name: arctiq-mission
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arctiq-mission-cicd
  namespace: arctiq-mission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-flask
  template:
    metadata:
      labels:
        app: python-flask
    spec:
      containers:
      - name: python-flask-app
        image: gcr.io/arctiq-mission-masrur/arctiq_mission/mdmasrur3426/arctiq-image:v1
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: python-flask
  namespace: arctiq-mission
spec:
  type: LoadBalancer
  selector:
    app: python-flask
  ports:
  - port: 80
    targetPort: 8080